# Generated by Django 2.2.2 on 2019-06-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmap',
            old_name='long_url',
            new_name='url',
        ),
    ]
